### ISSUE TITLE
[FIX] Format Unix Timestamp to Hours/Minutes/Seconds

### ISSUE THREAD

**Issue by DataBass504** [DataBass504/robo-bro#1]
last_updated currently pulls Unix timestamp from CoinMarketCap API, this needs to be set to read in seconds, minutes, & hours.
Code can be found in coin_market.py file on line 65.

formatted_data += 'Updated: {}```\n' .format(float(data['last_updated']))

**Comment by alxwrd** [comment]
I can take a look at this if you like.

Would you rather an implementation using the standard library, or would another dependency be ok?

**Comment by DataBass504** [comment]
That would be great! Should be fairly easy, to be honest I haven't touched code in 10+ years & I'm new to python so any help would be greatly appreciated. I have another guy that will be jumping in to help build new features for our discord bot soonish, whatever would be easier for you as long as it works. Basically right now it sends to discord like this:

Price (USD): $0.271638
Price (BTC): ฿0.00001779
Market Cap (USD): $4,851,122,899.0
Available Supply: 17,858,778,590.0
(1H): 5.29% (24H): 5.71% (7D): 47.57%
Updated: 1513904648.0

I'd like the line Updated to look like:
Updated: 1h 20m 30s ago

Thanks in advance!

**Comment by DataBass504** [comment]
Timestamp formated, thanks valin!
