### ISSUE TITLE
[Addition] Search Command By Coin Symbol or Coin ID

### ISSUE THREAD

**Issue by DataBass504** [DataBass504/robo-bro#2]
I'd like to add an addition to the search command for searching coins to also support coin symbols, this can be done by once a coin is searched using full ID it'll add the coin symbol to a list. I believe this can be done in the command_handler.py file. I did notice that some coins share the same symbols but this is very rare.

**Comment by valinsky** [comment]
i can work on this

**Comment by DataBass504** [comment]
Cool, thanks valin I believe "symbols" is pulled from CoinMarketCap API.

**Comment by DataBass504** [comment]
Addition complete, very wow.
